# Author : Francesco Seccamonte
# Copyright (c) 2019 Francesco Seccamonte. All rights reserved.  
# Licensed under the MIT License. See LICENSE file in the project root for full license information.  
# 

sudo: required
language: cpp

services:
  - docker

env:
  # used to setup a build matrix
  - COMPILER=gcc7
  - COMPILER=gcc8

before_install:
  # Pull image
  - docker pull conanio/$COMPILER
  # Start container
  - docker run -itd --name build$COMPILER conanio/$COMPILER
  # Configure conan
  - docker exec build$COMPILER bash -c 'conan profile new default --detect; conan profile update settings.compiler.libcxx=libstdc++11 default'
  # Clone repo
  - docker exec build$COMPILER git clone https://github.com/francescoseccamonte/cpp-travis-integration.git /repo

script:
  - docker exec build$COMPILER mkdir /repo/build
  - docker exec -w repo/build build$COMPILER conan install -o cpp-travis-integration:build_tests=True ..
  - docker exec -w /repo/build build$COMPILER cmake ..
  - docker exec -w /repo/build build$COMPILER cmake --build .
  - docker exec -w /repo/build build$COMPILER ctest

after_success:
  # Create a conan package containing the project
  - docker exec -w /repo build$COMPILER conan create francesco/testing ..
